name: Deploy

on:
  push:
    paths:
      - 'terraform/**'
    branches: [test]
  pull_request:
    paths:
      - 'terraform/**'
    branches: [test]

jobs:
  Terraform:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./terraform
    name: Terraform Plan & Apply
    steps:

    - name: Checkout Repo
      uses: actions/checkout@v2

    - name: Terraform Setup
      uses: hashicorp/setup-terraform@v1
      
    - name: Terraform Init
      id: init
      run: terraform init
      working-directory: terraform
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        # TF_ACTION_WORKING_DIR: '/terraform'
        AWS_ACCESS_KEY_ID:  ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY:  ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        
    - name: Terraform Validate
      run: terraform validate

    - name: Terraform Plan
      id: plan
      run: terraform plan
      working-directory: terraform
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        # TF_ACTION_WORKING_DIR: '/terraform'
        AWS_ACCESS_KEY_ID:  ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY:  ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        
    - name: Terraform Apply
      id: apply
      working-directory: terraform
      run: terraform apply -auto-approve
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        # TF_ACTION_WORKING_DIR: '/terraform'
        AWS_ACCESS_KEY_ID:  ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY:  ${{ secrets.AWS_SECRET_ACCESS_KEY }}